#!/usr/bin/env bash

test_description="emacs interface"
. test-lib.sh

EXPECTED=$TEST_DIRECTORY/pick.expected-output

add_email_corpus

test_begin_subtest "Basic notmuch-pick view in emacs"
test_emacs '(require (quote notmuch-pick))
            (notmuch-pick "tag:inbox")
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-tag-inbox

test_begin_subtest "Basic notmuch-pick view in emacs (sync)"
test_emacs '(setq notmuch-pick-asynchronous-parser nil)
            (notmuch-pick "tag:inbox")
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-tag-inbox

test_begin_subtest "Navigation of notmuch-hello to search results"
test_emacs '(notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
	    (notmuch-pick-from-search-current-query)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-tag-inbox

test_begin_subtest "Navigation of notmuch-hello to search results (sync)"
test_emacs '(setq notmuch-pick-asynchronous-parser nil)
            (notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
	    (notmuch-pick-from-search-current-query)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-tag-inbox

test_begin_subtest "Pick of a single thread (from search)"
test_emacs '(notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
            (notmuch-pick-from-search-thread)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-single-thread

test_begin_subtest "Pick of a single thread (sync from search)"
test_emacs '(setq notmuch-pick-asynchronous-parser nil)
            (notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
            (notmuch-pick-from-search-thread)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-single-thread

test_begin_subtest "Pick of a single thread (from show)"
test_emacs '(notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
	    (notmuch-search-show-thread)
            (notmuch-pick-from-show-current-query)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-single-thread-2

test_begin_subtest "Pick of a single thread (sync from show)"
test_emacs '(setq notmuch-pick-asynchronous-parser nil)
            (notmuch-hello)
            (goto-char (point-min))
            (re-search-forward "inbox")
            (widget-button-press (1- (point)))
            (notmuch-test-wait)
	    (notmuch-search-show-thread)
            (notmuch-pick-from-show-current-query)
            (notmuch-test-wait)
            (test-output)'
test_expect_equal_file OUTPUT $EXPECTED/notmuch-pick-single-thread-2

test_done
